- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
      - sanemat/font
    homebrew_packages:
      - { name: autoconf }
      # - { name: automake }
      - { name: awscli }
      # - {name: apple-gcc42}
      # - {name: boot2docker }
      # - { name: bundler-completion }
      # - { name: boost }
      # - { name: cairo }
      - { name: curl }
      # - {name: cloog }
      # - { name: cmake }
      # - { name: crf++ }
      # - { name: ctags }
      # - { name: coreutils }
      - { name: direnv }
      - { name: docker-compose }
      # - { name: eigen }
      # - { name: editorconfig }
      # - { name: elixir }
      # - { name: fontconfig }
      # - { name: freetype }
      # - { name: flow }
      - { name: ffmpeg }
      - { name: freetype }
      # - { name: gcc }
      # - {name: gcc47}
      - { name: gettext }
      - { name: git }
      - { name: git-lfs }
      - { name: goenv }
      # - { name: glib }
      # - { name: gd }
      # - { name: gdbm }
      # - { name: gmp }
      # - { name: gmp4 }
      # - { name: graphviz }
      # - { name: hub }
      # - { name: homebrew/completions/vagrant-completion }
      - { name: imagemagick }
      # - {name: isl }
      - { name: jpeg }
      # - { name: jq }
      # - { name: jsonpp }
      - { name: lame }
      - { name: libevent }
      - { name: libffi }
      - { name: libidn2 }
      - { name: libogg }
      - { name: libomp }
      - { name: libpng }
      - { name: libtiff }
      - { name: libtool }
      # - { name: libsodium }
      - { name: libunistring }
      - { name: libvorbis }
      - { name: libvpx }
      - { name: libyaml }
      - { name: little-cms2 }
      - { name: lua }
      # - { name: lv }
      # - { name: mercurial }
      # - {name: mpfr2}
      - { name: mysql }
      - { name: nkf }
      - { name: nodebrew }
      - { name: openjpeg }
      - { name: openssl }
      # - { name: openssl, state: linked, install_options: force }
      - { name: opus }
      # - { name: packer }
      # - { name: peco }
      # - { name: pip-completion }
      - { name: pcre2 }
      - { name: perl }
      - { name: pkg-config }
      - { name: pyenv }
      # - { name: p7zip }
      # - {name: ricty}
      - { name: readline }
      - { name: rmtrash }
      - { name: ruby }
      # - { name: rake-completion }
      # - { name: rails-completion }
      # - { name: rbenv }
      # - { name: rbenv-gem-rehash }
      # - { name: rbenv-gemset }
      # - { name: reattach-to-user-namespace }
      # - { name: rlwrap }
      # - { name: ruby-completion }
      # - { name: ruby-build }
      # - { name: rsense }
      # - { name: rsense, state: linked, install_options: force }
      # - { name: socat }
      # - { name: subversion}
      - { name: sdl2 }
      - { name: snappy }
      - { name: sqlite }
      - { name: source-highlight }
      - { name: theora }
      # - { name: tig }
      - { name: tmux }
      # - { name: tofrodos }
      - { name: vim}
      - { name: webp }
      - { name: wget }
      - { name: x264 }
      - { name: x265 }
      - { name: xvid }
      - { name: xz }
      - { name: yarn }
      # - { name: watch }
      # - { name: w3m }
      # - { name: zsh, install_options: disable-etcdir }
    homebrew_cask_packages:
      - { name: android-file-transfer }
      - { name: android-sdk }
      - { name: android-studio }
      - { name: appcleaner }
      - { name: atom }
      - { name: avast-security }
      - { name: blender }
      # - { name: adobe-reader }
      # - { name: atom-shell }
      # - { name: calibr }
      - { name: cyberduck }
      - { name: docker }
      - { name: dropbox }
      - { name: gimp }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: iina }
      - { name: java }
      - { name: java8 }
      - { name: libreoffice }
      - { name: skitch }
      - { name: slack }
      - { name: the-unarchiver }
      - { name: unity-hub }
      - { name: visual-studio-code }
      # - { name: dash }
      # - { name: day-o }
      # - { name: onyx }
      # - { name: evernote }
      # - { name: macs-fan-control }
      # - { name: flux }
      # - { name: gyazo }
      - { name: kindle }
      # - { name: kindle-previewer }
      # - { name: monolingual }
      # - { name: seil }
      # - { name: skype }
      # - { name: skitch }
      # - { name: seashore }
      # - { name: vagrant }
      # - { name: virtualbox }
  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    Ricty
    - name: xquartz のインストール (for Ricty)
      homebrew_cask: name=xquartz
    - name: fontforge のインストール (for Ricty)
      homebrew: name=fontforge
    - name: Ricty のインストール
      homebrew: name=ricty
    - name: 生成されたフォントファイルをコピー
      shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
      args:
        creates: ~/Library/Fonts/Ricty-Bold.ttf
      notify: run fc-cache

  handlers:
    - name: run fc-cache
      shell: fc-cache -vf
